{% set name = "prms_groundwater" %}
{% set version = "0.2" %}
{% set build_number = "0" %}
{% set development = false %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/nhm-usgs/bmi-prms6-groundwater
{%- if development %}
  git_rev: 27305cd2cadd20b2c48e35f64f901a046809d8a2
{%- else %}
  git_rev: v{{ version }}
{%- endif %}

build:
{%- if development %}
  string: beta_{{ build_number }}
{%- else %}
  number: {{ build_number }}
{%- endif %}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('fortran') }}
    - libnetcdf
    - netcdf-fortran
  host:
    - libnetcdf
    - netcdf-fortran
    - coretran
    - prms
  run:
    - libnetcdf
    - netcdf-fortran
    - coretran
    - prms

test:
  commands:
    - test -s $PREFIX/lib/libbmiprmsgroundwater$SHLIB_EXT
    - test -s $PREFIX/include/bmif_2_0.mod
    - test -s $PREFIX/include/bmiprmsgroundwater.mod

about:
  home: https://www.usgs.gov/software/precipitation-runoff-modeling-system-prms
  license: CCO 1.0 Universal
  license_file: License.md
  summary: USGS Precipitation Runoff Modeling System (PRMS) Groundwater component
  description: |
    The Precipitation-Runoff Modeling System (PRMS) is a
    deterministic, distributed-parameter, physical process based
    modeling system developed to evaluate the response of various
    combinations of climate and land use on streamflow and general
    watershed hydrology. This version of PRMS has been
    refactored to use only the groundwater component, and it is
    equipped with a Basic Model Interface.
  dev_url: https://github.com/nhm-usgs/bmi-prms6-groundwater
